name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn build-all
      - uses: mattallty/jest-github-action@v1
        with:
          test-command: yarn test-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
